// Autogenerated 2018-09-18 23:59:24.917166

using System;


namespace GlmNet
{
#if DOUBLE_PRECISION
    using scalar = Double;
#else
    using scalar = Single;
#endif

    public readonly partial struct poly
	{
        /// <summary>
        /// Returns the Hurwitz Matrix associated with this polynomial
        /// </summary>
	    public dynamic HurwitzMatrix
		{
		    get
			{
			    // TODO : fix this

			    switch (Degree)
				{
				    case -1:
				    case 0:
                        throw new InvalidOperationException("The Hurwitz matrix is not defined for polynomials of degree zero.");
				    case 1:
					    return LeadingCoefficient;
                    case 2:
				        return new mat2(
			                _coeff[ 1], 0,
			                _coeff[ 0], _coeff[ 2]
					    );
                    case 3:
				        return new mat3(
			                _coeff[ 1], _coeff[ 3], 0,
			                _coeff[ 0], _coeff[ 2], 0,
			                0,          _coeff[ 1], _coeff[ 3]
					    );
                    case 4:
				        return new mat4(
			                _coeff[ 1], _coeff[ 3], 0,          0,
			                _coeff[ 0], _coeff[ 2], _coeff[ 4], 0,
			                0,          _coeff[ 1], _coeff[ 3], 0,
			                0,          _coeff[ 0], _coeff[ 2], _coeff[ 4]
					    );
                    case 5:
				        return new mat5(
			                _coeff[ 1], _coeff[ 3], _coeff[ 5], 0,          0,
			                _coeff[ 0], _coeff[ 2], _coeff[ 4], 0,          0,
			                0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], 0,
			                0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], 0,
			                0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5]
					    );
                    case 6:
				        return new mat6(
			                _coeff[ 1], _coeff[ 3], _coeff[ 5], 0,          0,          0,
			                _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], 0,          0,
			                0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], 0,          0,
			                0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], 0,
			                0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], 0,
			                0,          0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6]
					    );
                    case 7:
				        return new mat7(
			                _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], 0,          0,          0,
			                _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], 0,          0,          0,
			                0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], 0,          0,
			                0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], 0,          0,
			                0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], 0,
			                0,          0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], 0,
			                0,          0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7]
					    );
                    case 8:
				        return new mat8(
			                _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], 0,          0,          0,          0,
			                _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], 0,          0,          0,
			                0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], 0,          0,          0,
			                0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], 0,          0,
			                0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], 0,          0,
			                0,          0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], 0,
			                0,          0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], 0,
			                0,          0,          0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8]
					    );
                    case 9:
				        return new mat9(
			                _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9], 0,          0,          0,          0,
			                _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], 0,          0,          0,          0,
			                0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9], 0,          0,          0,
			                0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], 0,          0,          0,
			                0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9], 0,          0,
			                0,          0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], 0,          0,
			                0,          0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9], 0,
			                0,          0,          0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], 0,
			                0,          0,          0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9]
					    );
                    case 10:
				        return new mat10(
			                _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9], 0,          0,          0,          0,          0,
			                _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], _coeff[10], 0,          0,          0,          0,
			                0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9], 0,          0,          0,          0,
			                0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], _coeff[10], 0,          0,          0,
			                0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9], 0,          0,          0,
			                0,          0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], _coeff[10], 0,          0,
			                0,          0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9], 0,          0,
			                0,          0,          0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], _coeff[10], 0,
			                0,          0,          0,          0,          _coeff[ 1], _coeff[ 3], _coeff[ 5], _coeff[ 7], _coeff[ 9], 0,
			                0,          0,          0,          0,          _coeff[ 0], _coeff[ 2], _coeff[ 4], _coeff[ 6], _coeff[ 8], _coeff[10]
					    );
                    default:
				        throw new NotImplementedException();
				}
			}
		}

		public static implicit operator poly((scalar _0, scalar _1) t) =>
		    new poly(t._0, t._1);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2) t) =>
		    new poly(t._0, t._1, t._2);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3) t) =>
		    new poly(t._0, t._1, t._2, t._3);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53, scalar _54) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53, t._54);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53, scalar _54, scalar _55) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53, t._54, t._55);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53, scalar _54, scalar _55, scalar _56) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53, t._54, t._55, t._56);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53, scalar _54, scalar _55, scalar _56, scalar _57) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53, t._54, t._55, t._56, t._57);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53, scalar _54, scalar _55, scalar _56, scalar _57, scalar _58) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53, t._54, t._55, t._56, t._57, t._58);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53, scalar _54, scalar _55, scalar _56, scalar _57, scalar _58, scalar _59) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53, t._54, t._55, t._56, t._57, t._58, t._59);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53, scalar _54, scalar _55, scalar _56, scalar _57, scalar _58, scalar _59, scalar _60) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53, t._54, t._55, t._56, t._57, t._58, t._59, t._60);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53, scalar _54, scalar _55, scalar _56, scalar _57, scalar _58, scalar _59, scalar _60, scalar _61) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53, t._54, t._55, t._56, t._57, t._58, t._59, t._60, t._61);
		public static implicit operator poly((scalar _0, scalar _1, scalar _2, scalar _3, scalar _4, scalar _5, scalar _6, scalar _7, scalar _8, scalar _9, scalar _10, scalar _11, scalar _12, scalar _13, scalar _14, scalar _15, scalar _16, scalar _17, scalar _18, scalar _19, scalar _20, scalar _21, scalar _22, scalar _23, scalar _24, scalar _25, scalar _26, scalar _27, scalar _28, scalar _29, scalar _30, scalar _31, scalar _32, scalar _33, scalar _34, scalar _35, scalar _36, scalar _37, scalar _38, scalar _39, scalar _40, scalar _41, scalar _42, scalar _43, scalar _44, scalar _45, scalar _46, scalar _47, scalar _48, scalar _49, scalar _50, scalar _51, scalar _52, scalar _53, scalar _54, scalar _55, scalar _56, scalar _57, scalar _58, scalar _59, scalar _60, scalar _61, scalar _62) t) =>
		    new poly(t._0, t._1, t._2, t._3, t._4, t._5, t._6, t._7, t._8, t._9, t._10, t._11, t._12, t._13, t._14, t._15, t._16, t._17, t._18, t._19, t._20, t._21, t._22, t._23, t._24, t._25, t._26, t._27, t._28, t._29, t._30, t._31, t._32, t._33, t._34, t._35, t._36, t._37, t._38, t._39, t._40, t._41, t._42, t._43, t._44, t._45, t._46, t._47, t._48, t._49, t._50, t._51, t._52, t._53, t._54, t._55, t._56, t._57, t._58, t._59, t._60, t._61, t._62);
	}
}
